

import {
    DiAndroid,
    DiAngularSimple,
    DiAppcelerator,
    DiApple,
    DiAppstore,
    DiAptana,
    DiAsterisk,
    DiAtlassian,
    DiAtom,
    DiAws,
    DiBackbone,
    DiBingSmall,
    DiBintray,
    DiBitbucket,
    DiBlackberry,
    DiBootstrap,
    DiBower,
    DiBrackets,
    DiBugsense,
    DiCelluloid,
    DiChrome,
    DiCisco,
    DiClojureAlt,
    DiClojure,
    DiCloud9,
    DiCoda,
    DiCodeBadge,
    DiCode,
    DiCodeigniter,
    DiCodepen,
    DiCodrops,
    DiCoffeescript,
    DiCompass,
    DiComposer,
    DiCreativecommonsBadge,
    DiCreativecommons,
    DiCssTricks,
    DiCss3Full,
    DiCss3,
    DiCssdeck,
    DiDart,
    DiDatabase,
    DiDebian,
    DiDigitalOcean,
    DiDjango,
    DiDlang,
    DiDocker,
    DiDoctrine,
    DiDojo,
    DiDotnet,
    DiDreamweaver,
    DiDropbox,
    DiDrupal,
    DiEclipse,
    DiEmber,
    DiEnvato,
    DiErlang,
    DiExtjs,
    DiFirebase,
    DiFirefox,
    DiFsharp,
    DiGhostSmall,
    DiGhost,
    DiGitBranch,
    DiGitCommit,
    DiGitCompare,
    DiGitMerge,
    DiGitPullRequest,
    DiGit,
    DiGithubAlt,
    DiGithubBadge,
    DiGithubFull,
    DiGithub,
    DiGnu,
    DiGo,
    DiGoogleAnalytics,
    DiGoogleDrive,
    DiGoogleCloudPlatform,
    DiGrails,
    DiGroovy,
    DiGrunt,
    DiGulp,
    DiHackernews,
    DiHaskell,
    DiHeroku,
    DiHtml53dEffects,
    DiHtml5Connectivity,
    DiHtml5DeviceAccess,
    DiHtml5Multimedia,
    DiHtml5,
    DiIe,
    DiIllustrator,
    DiIntellij,
    DiIonic,
    DiJava,
    DiJavascript1,
    DiJavascript,
    DiJekyllSmall,
    DiJenkins,
    DiJira,
    DiJoomla,
    DiJqueryLogo,
    DiJqueryUiLogo,
    DiJsBadge,
    DiKomodo,
    DiKrakenjsBadge,
    DiKrakenjs,
    DiLaravel,
    DiLess,
    DiLinux,
    DiMagento,
    DiMailchimp,
    DiMarkdown,
    DiMaterializecss,
    DiMeteor,
    DiMeteorfull,
    DiMitlicence,
    DiModernizr,
    DiMongodb,
    DiMootoolsBadge,
    DiMootools,
    DiMozilla,
    DiMsqlServer,
    DiMysql,
    DiNancy,
    DiNetbeans,
    DiNetmagazine,
    DiNginx,
    DiNodejsSmall,
    DiNodejs,
    DiNpm,
    DiOnedrive,
    DiOpenshift,
    DiOpensource,
    DiOpera,
    DiPerl,
    DiPhonegap,
    DiPhotoshop,
    DiPhp,
    DiPostgresql,
    DiProlog,
    DiPython,
    DiRackspace,
    DiRaphael,
    DiRasberryPi,
    DiReact,
    DiRedhat,
    DiRedis,
    DiRequirejs,
    DiResponsive,
    DiRor,
    DiRubyRough,
    DiRuby,
    DiRust,
    DiSafari,
    DiSass,
    DiScala,
    DiScriptcs,
    DiScrum,
    DiSenchatouch,
    DiSizzlejs,
    DiSmashingMagazine,
    DiSnapSvg,
    DiSpark,
    DiSqllite,
    DiStackoverflow,
    DiStreamline,
    DiStylus,
    DiSublime,
    DiSwift,
    DiSymfonyBadge,
    DiSymfony,
    DiTechcrunch,
    DiTerminalBadge,
    DiTerminal,
    DiTravis,
    DiTrello,
    DiTypo3,
    DiUbuntu,
    DiUikit,
    DiUnitySmall,
    DiVim,
    DiVisualstudio,
    DiW3C,
    DiWebplatform,
    DiWindows,
    DiWordpress,
    DiYahooSmall,
    DiYahoo,
    DiYeoman,
    DiYii,
    DiZend
} from "react-icons/di";
import React from 'react';

const iconMap: Record<string, React.ComponentType> = {
    'android': DiAndroid,
    'angularsimple': DiAngularSimple,
    'appcelerator': DiAppcelerator,
    'apple': DiApple,
    'appstore': DiAppstore,
    'aptana': DiAptana,
    'asterisk': DiAsterisk,
    'atlassian': DiAtlassian,
    'atom': DiAtom,
    'aws': DiAws,
    'backbone': DiBackbone,
    'bingsmall': DiBingSmall,
    'bintray': DiBintray,
    'bitbucket': DiBitbucket,
    'blackberry': DiBlackberry,
    'bootstrap': DiBootstrap,
    'bower': DiBower,
    'brackets': DiBrackets,
    'bugsense': DiBugsense,
    'celluloid': DiCelluloid,
    'chrome': DiChrome,
    'cisco': DiCisco,
    'clojurealt': DiClojureAlt,
    'clojure': DiClojure,
    'cloud9': DiCloud9,
    'coda': DiCoda,
    'codebadge': DiCodeBadge,
    'code': DiCode,
    'codeigniter': DiCodeigniter,
    'codepen': DiCodepen,
    'codrops': DiCodrops,
    'coffeescript': DiCoffeescript,
    'compass': DiCompass,
    'composer': DiComposer,
    'creativecommonsbadge': DiCreativecommonsBadge,
    'creativecommons': DiCreativecommons,
    'csstricks': DiCssTricks,
    'css3full': DiCss3Full,
    'css3': DiCss3,
    'cssdeck': DiCssdeck,
    'dart': DiDart,
    'database': DiDatabase,
    'debian': DiDebian,
    'digitalocean': DiDigitalOcean,
    'django': DiDjango,
    'dlang': DiDlang,
    'docker': DiDocker,
    'doctrine': DiDoctrine,
    'dojo': DiDojo,
    'dotnet': DiDotnet,
    'dreamweaver': DiDreamweaver,
    'dropbox': DiDropbox,
    'drupal': DiDrupal,
    'eclipse': DiEclipse,
    'ember': DiEmber,
    'envato': DiEnvato,
    'erlang': DiErlang,
    'extjs': DiExtjs,
    'firebase': DiFirebase,
    'firefox': DiFirefox,
    'fsharp': DiFsharp,
    'ghostsmall': DiGhostSmall,
    'ghost': DiGhost,
    'gitbranch': DiGitBranch,
    'gitcommit': DiGitCommit,
    'gitcompare': DiGitCompare,
    'gitmerge': DiGitMerge,
    'gitpullrequest': DiGitPullRequest,
    'git': DiGit,
    'githubalt': DiGithubAlt,
    'githubbadge': DiGithubBadge,
    'githubfull': DiGithubFull,
    'github': DiGithub,
    'gnu': DiGnu,
    'go': DiGo,
    'googleanalytics': DiGoogleAnalytics,
    'googledrive': DiGoogleDrive,
    'googlecloudplatform': DiGoogleCloudPlatform,
    'grails': DiGrails,
    'groovy': DiGroovy,
    'grunt': DiGrunt,
    'gulp': DiGulp,
    'hackernews': DiHackernews,
    'haskell': DiHaskell,
    'heroku': DiHeroku,
    'html53deffects': DiHtml53dEffects,
    'html5connectivity': DiHtml5Connectivity,
    'html5deviceaccess': DiHtml5DeviceAccess,
    'html5multimedia': DiHtml5Multimedia,
    'html5': DiHtml5,
    'ie': DiIe,
    'illustrator': DiIllustrator,
    'intellij': DiIntellij,
    'ionic': DiIonic,
    'java': DiJava,
    'javascript1': DiJavascript1,
    'javascript': DiJavascript,
    'jekyllsmall': DiJekyllSmall,
    'jenkins': DiJenkins,
    'jira': DiJira,
    'joomla': DiJoomla,
    'jquerylogo': DiJqueryLogo,
    'jqueryuilogo': DiJqueryUiLogo,
    'jsbadge': DiJsBadge,
    'komodo': DiKomodo,
    'krakenjsbadge': DiKrakenjsBadge,
    'krakenjs': DiKrakenjs,
    'laravel': DiLaravel,
    'less': DiLess,
    'linux': DiLinux,
    'magento': DiMagento,
    'mailchimp': DiMailchimp,
    'markdown': DiMarkdown,
    'materializecss': DiMaterializecss,
    'meteor': DiMeteor,
    'meteorfull': DiMeteorfull,
    'mitlicence': DiMitlicence,
    'modernizr': DiModernizr,
    'mongodb': DiMongodb,
    'mootoolsbadge': DiMootoolsBadge,
    'mootools': DiMootools,
    'mozilla': DiMozilla,
    'msqlserver': DiMsqlServer,
    'mysql': DiMysql,
    'nancy': DiNancy,
    'netbeans': DiNetbeans,
    'netmagazine': DiNetmagazine,
    'nginx': DiNginx,
    'nodejssmall': DiNodejsSmall,
    'nodejs': DiNodejs,
    'npm': DiNpm,
    'onedrive': DiOnedrive,
    'openshift': DiOpenshift,
    'opensource': DiOpensource,
    'opera': DiOpera,
    'perl': DiPerl,
    'phonegap': DiPhonegap,
    'photoshop': DiPhotoshop,
    'php': DiPhp,
    'postgresql': DiPostgresql,
    'prolog': DiProlog,
    'python': DiPython,
    'rackspace': DiRackspace,
    'raphael': DiRaphael,
    'raspberrypi': DiRasberryPi,
    'react': DiReact,
    'redhat': DiRedhat,
    'redis': DiRedis,
    'requirejs': DiRequirejs,
    'responsive': DiResponsive,
    'ror': DiRor,
    'rubyr': DiRubyRough,
    'ruby': DiRuby,
    'rust': DiRust,
    'safari': DiSafari,
    'sass': DiSass,
    'scala': DiScala,
    'scriptcs': DiScriptcs,
    'scrum': DiScrum,
    'senchatouch': DiSenchatouch,
    'sizzlejs': DiSizzlejs,
    'smashingmagazine': DiSmashingMagazine,
    'snapsvg': DiSnapSvg,
    'spark': DiSpark,
    'sqllite': DiSqllite,
    'stackoverflow': DiStackoverflow,
    'streamline': DiStreamline,
    'stylus': DiStylus,
    'sublime': DiSublime,
    'swift': DiSwift,
    'symfonybadge': DiSymfonyBadge,
    'symfony': DiSymfony,
    'techcrunch': DiTechcrunch,
    'terminalbadge': DiTerminalBadge,
    'terminal': DiTerminal,
    'travis': DiTravis,
    'trello': DiTrello,
    'typo3': DiTypo3,
    'ubuntu': DiUbuntu,
    'uikit': DiUikit,
    'unitysmall': DiUnitySmall,
    'vim': DiVim,
    'visualstudio': DiVisualstudio,
    'w3c': DiW3C,
    'webplatform': DiWebplatform,
    'windows': DiWindows,
    'wordpress': DiWordpress,
    'yahoosmall': DiYahooSmall,
    'yahoo': DiYahoo,
    'yeoman': DiYeoman,
    'yii': DiYii,
    'zend': DiZend
};



export default iconMap;